---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: playground-fluxcd-helm-app-dev
  namespace: playground
spec:
  interval: 10s
  driftDetection:
  mode: enabled
  chart:
    spec:
      chart: ./apps/base/playground/fluxcd/helm-app   # local path in repo
      reconcileStrategy: Revision # updates when anything changes in the chart directory
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - ./apps/base/playground/fluxcd/helm-app/values/dev.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: playground-fluxcd-helm-app-prod
  namespace: playground
spec:
  interval: 10s
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./apps/base/playground/fluxcd/helm-app   # local path in repo
      reconcileStrategy: ChartVersion # updates when chart version changes
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - ./apps/base/playground/fluxcd/helm-app/values/prod.yaml
