---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yoga-root
  namespace: host-access
spec:
  serviceName: yoga-root
  replicas: 1
  selector:
    matchLabels:
      name: yoga-root
  template:
    metadata:
      labels:
        name: yoga-root
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: yoga-root
        image: ubuntu:latest
        command: ["sleep", "infinity"]
        stdin: true
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: host
        hostPath:
          path: /
      restartPolicy: Always