---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            ollama serve &;
            sleep 10;
            ollama pull gemma3:1b;
            wait; # waits for background processes to finish before container exits
        ports:
        - containerPort: 11434