---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      volumes:
        - name: ollama-pvc
          persistentVolumeClaim:
            claimName: ollama-pvc
      initContainers:
        - name: ollama-model-puller
          image: ollama/ollama:latest
          # command: ["ollama", "pull", "gemma3:1b"]
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-pvc
              mountPath: /root/.ollama
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        volumeMounts:
          - name: ollama-pvc
            mountPath: /root/.ollama
