---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 11434
    nodePort: 32434
  selector:
    name: ollama