apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: n8n
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
