---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-db-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgB4jSicTlUi3yTaSA2jHBe2RQwQIbyl5W8Vhe7APRV3oEovvJbho8e4qEHvxCSzQxU2pyK9U6TGt2xcj/Skp1WsMEyu3dNOWoxZ/W3JPLRXQ96wZLwStRt8T+/cwla1nwYl7o9fyEk90VljnlecXPVXeJSPgs1CrWkYmvBqIRwwh1APqLgDXyohMTy18hjOji/q7I5ONZvdeANHgnhfjaJHsODgbxgIlWYz+iD5hiwp3epHoiURyY6cwqIQmAW1bDwLlEyevNLaqQY/g1Wvhe3wce/2YKrDVr6gKVk+Ov76su1fSbTb5CDCY7R3BIAfBdQYV210yyoCr8vxcNLhlYLBUoL/oPMzqhwuOw/dy+A+U2ZfZz2/BC0T1t4DhdN3AGnutjU8H5wfxhHzsgKFNwBgapfQdE4SaPOu0TWUFrfdyuLD8m42/AABbksN/PC77C2uMXx5ofRaafGyaJVejrgJxzaqT/k8oBIstPwkTebbi0KIfXFhp2ptcimhDsJgKPCVhZZ+XYB1AJ9odAkZhLAHY3gQhc9l5cLr6hEuxajdMrZfxMHeaPJB9Dg9vpa8mizQgpgLBBMHO4dFyyBjhVqXrQcRkYvWEacc87TORNWCUKxzTq11t/r/EwkTQEV2VxuFh0lSNERvhYa9Q9PfW/aH+0ciD8DZnolqM8lelXJYBn+TaP9KNZNbZiZuupqaWq3TOQbJXsJHDClJeQ==
    username: AgBpDuHw3bKqUN4rGURCEOS3RyC9OGEKGLQ8YluRxhGlr+RegQ6CGwaSy2v/lFbSPHJSMwWsRX6OfgwFTjHvHsezzbT5YTtg1Scz71EFdFM4KelcV8faqk6D1DMuw4dDMRHyUg7RHa1r2I4Z0qVWOUtDkXRhX7x2sDLcHfEiyLiS0mb94eJPj+d+Dv9ysj+NZbFnzJsxFCBqnFPJYrgN+4G9nQwsLbrPtAROybSXonLrj56bTzvys2eZn/pxksoMAxZ4dvm6m/lCtXVzX5tY2Tx1pgyz3MZVuV+zsCb9oBNhRyYdM0t5xoPOMZ3KU769NTowi1ZdcbkXjait66pJnfGBPZiuSKUq1PjYcGd1YqxTl0XC4vZBM9rqtsk4TFeXiv4ek819Qdu1rrc+1UwlfPeeHD2tDqbzRXPd0h//nmhOkdYSp/1A3qXg5ZMrog0LSWAre4MecO0r/qfKKUPyOU8pylI/LrL/zyDAW5fqsN9u57SP1m/WI5CiCVAk3kwxqR8n4p6Zo6WrN6wowBXayPcjTZxrZ13Jy5BX0wX5mmDdpf0XDKjhzww0v8JNAs3hm5mwurFr74LAxdvN0YW0/t5fBc3Mzk+BV3bVGo5OQDJKlCDJmVfBieW5YuoDP24Ef4HWyCLIHDuCTsuAN5Y6UBA41nZULZ9spToKKkvLxRAH4j42d4XvFzIrgvU+CKnDhsBiJuo=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-db-secret
      namespace: n8n