---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 32678
  selector:
    service: n8n