---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: key-sync
  name: key-sync-claim
  namespace: key-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi