---
apiVersion: v1
kind: Service
metadata:
  name: key-sync
  namespace: key-sync
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
  selector:
    app: key-sync