---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cloudflare
spec:
  encryptedData:
    tunnel-token-yoga: AgBVJi9mD/kHObI63/w22p8d0LM/0Du6UxXqlIurYPT1qIdtktnyR4D6nlnUwiV5QLi5EGWz31hc/KJI9Op/u2GjHkhD+QR0Da+dzL6woIeD1ePGotT44nqx3pEdscvRPqqSVimVNPWbU3kt7Vg1vfPpuMd+/IhW5AJAdaseqnIlUwHjJygvpHs+ccTy1rCm3TMxXSXSO+5vzSKSCf28TkGnspHXjjWhhKW3V0mMiO1YoZSu4VXsyaCkNo6GBpEanG/NeOIensfhqpAAYrPygxxztsb8ufpWsDR8kyfUE0VBPVdTa+wlHvqbKi017vlUAoBBFv8TJq03p0TZYkq+1fd8WdhVMZ8deCSG/91EKIQuaUkW4kiiB1o8OycymzMMRz/U9TIydO3K0uHtsA4g6Z5IZrEf+f34SMYK+UFMe6Cq1YJsLFni1Ut6xnixFbG6WAdfMLQkTbDA7qqeGoqnwuSnFM0KbcQ373qZ+KIxOeJfqoGMruX5lOVsWP0OFgcy6eZd5sLqj2EdvmZdzJ6Qu2vG9PW7sx2r4XE9vHHllsOaRHdxWneMH0bMXYkWpDhnwx8O3CpgktqAObtcfQY3Te+Y368rJ0Z0sgQFnKNVUk7OAL4HrUkrIFggkp0sb+jGz0QREakXXA+j3oaSBxEiKSPe46GVtFB8aiDiAdvz+wznPVu9OA8MaOvJIyX95at5tKpbYsHkmNWhwNHO33WLRYOpf3Chx3vwGb2lyT2kzJ03RzdOA7gox8F8DO3Cfd1tYsrBRG+qeQjOk7u2fIi3Nf2w2AgwwT1c2aRipMO8Eh+4fjU7EM4EfrRNd8qOh910lDTL1MgpNnz0RLPYTzcld8AQ0PC7LXOZlqtFHO497s9Vc3zwbW8twdokBXqxB8HpdFKkfx0gbMO+mZKvF1d021X44Ar6l5pOiWuASTwKRKgDCAKf2im8mwaX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cloudflare
