mod sops 'modules/sops'
mod age 'modules/age'
mod opencode 'modules/opencode'
mod cloudflared 'modules/cloudflared'
mod haproxy 'modules/haproxy'

default:
  @just --list

bootstrap:
  ./bootstrap.sh

