---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://cloudnative-pg.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: cnpg
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: '*'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cnpg-controller
  targetNamespace: cnpg-system
  createNamespace: true
  upgrade:
    crds: CreateReplace
