---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cockpit-ingress
  namespace: cockpit
spec:
  rules:
    - host: cockpit.nairvarun.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cockpit-service
                port:
                  number: 443