---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: database
spec:
  instances: 3
  storage:
    size: 5Gi
  managed:
    roles:
    - name: n8n
      ensure: present
      comment: n8n user
      login: true
      passwordSecret:
        name: pg-cluster-n8n