---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: database
spec:
  instances: 3
  storage:
    size: 5Gi
  managed:
    roles:
    - name: n8n
      ensure: present
      comment: n8n user
      login: true
      passwordSecret:
        name: pg-cluster-n8n
    - name: dante
      ensure: present
      comment: my database-side comment
      login: true
      superuser: false
      createdb: true
      createrole: false
      inherit: false
      replication: false
      bypassrls: false
      connectionLimit: 4
      validUntil: "2053-04-12T15:04:05Z"
      inRoles:
        - pg_monitor
        - pg_signal_backend
      passwordSecret:
        name: cluster-example-dante
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-with-roles
  namespace: database
spec:
  instances: 3
  storage:
    size: 1Gi
  managed:
    roles:
    - name: app
      createdb: true
      login: true
    - name: n8n
      ensure: present
      comment: n8n user
      login: true
      passwordSecret:
        name: pg-cluster-n8n
    - name: dante2222
      ensure: present
      comment: my database-side comment
      login: true
      superuser: false
      createdb: true
      createrole: false
      inherit: false
      replication: false
      bypassrls: false
      connectionLimit: 4
      validUntil: "2053-04-12T15:04:05Z"
      inRoles:
        - pg_monitor
        - pg_signal_backend
      passwordSecret:
        name: cluster-example-dante
---
apiVersion: v1
data:
  username: ZGFudGUzMzMz
  password: ZGFudGU=
kind: Secret
metadata:
  name: cluster-example-dante
  namespace: database
type: kubernetes.io/basic-auth