apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: playground
resources:
  - namespace.yaml
  - fluxcd/helm-app
  - fluxcd/kustomize-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configmaps
  namespace: playground-fluxcd-kustomize-app
spec:
  interval: 10s
  retryInterval: 5s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: playground-fluxcd-kustomize-app
  path: ./apps/base/playground/fluxcd/kustomize-app
  prune: true
  wait: true
